version: '2.1'

services:
  postgres:
    container_name: "support-postgres"
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "support"
      POSTGRES_PASSWORD: "mysecretpassword"
